### PR TITLE
fix #177 failed to parse ticket

### LINKED ISSUE #177: assume techjira as default custom protocol for commit messages
In case the complete commit message does not start with either:
* https://
* http://
* offline:
* techjira:
* GH-  

assume *techjira:* is meant.

### PR DESCRIPTION
**Pull request by taojang**
Fixes #177 

Right now every time application is started, all commits will be fetched and rechecked eventually updated in database. This is a bit dangerous when commits of one repository can not be fit into memory. In future we should use some stream based solution for that.

### CODE REVIEW

File: app/utility/TicketParser.scala [hunk 1]
```diff
@@ -17,8 +17,8 @@ trait TicketParser {
    */
   private val message = """(.*?)?"""
   private val offline = """(.*?offline:[\w*\.*/*\-*]+){1}"""
-  private val techJira = """(.*?techjira:|jira:){1}"""
-  private val jiraSpec = """(.*?[\w*\-*\\d*]+){1}"""
```
Comment (taojang) [inline app/utility/TicketParser.scala]: @lotharschulz I think the original regex for jira ticket number is very strange.

**Comment by lotharschulz** [comment]
pls consider these hotspots: https://www.codacy.com/app/our1944/kontrolletti_main/pullRequest?prid=217592

File: app/utility/TicketParser.scala (hunk 1 above)
Comment (lotharschulz) [inline app/utility/TicketParser.scala]: @taojang : its complex but according to what was discussed with @kanuku

File: app/module/Bootstrap.scala [hunk 2]
```diff
@@ -53,5 +54,9 @@ class BootstrapImpl @Inject() (actorSystem: ActorSystem,
     ()
```
Comment (lotharschulz) [inline app/module/Bootstrap.scala]: pls reconsider this

File: app/utility/TicketParser.scala [hunk 3]
```diff
@@ -17,8 +17,8 @@ trait TicketParser {
...
+  private val techJira = """(.*?techjira:|jira:){1}\s*"""
```
Comment (lotharschulz) [inline app/utility/TicketParser.scala]: pls consider making sure if prefixes 
```
techjira:
```
and 
```
jira:
```
are used, that those prefixes are the first substring in a message.
AFAIK, the reg exp could be 
```
^(techjira:|jira:){1}\s*
```
same for offline

File: app/utility/TicketParser.scala [hunk 4]
```diff
@@ -17,8 +17,8 @@ trait TicketParser {
...
+  private val jiraSpec = """(\w+-\d+){1}"""
```
Comment (lotharschulz) [inline app/utility/TicketParser.scala]: as above, pls consider 
```
^(\w+-\d+){1}
```

File: test/utility/TicketParserTest.scala [hunk 5]
```diff
@@ -42,6 +42,11 @@ class TicketParserTest extends FlatSpec with Matchers {
     val message = s"$spec $text"
     ticketParser.parse(github, project, repository, message) shouldBe Some(new Ticket(message, spec, None))
   }
+  it must "fallback to techjira for message without protocol" in {
+    val message = s"CHECK-111 $text"
+    val result = Ticket(message, jira + "CHECK-111", None)
+    ticketParser.parse(github, project, repository, message) shouldBe Some(result)
+  }
```
Comment (lotharschulz) [inline test/utility/TicketParserTest.scala]: what about 
```
it must "not fallback to techjira for message without protocol" in {
    val message = s" CHECK-111 $text"
    val result = Ticket(message, jira + " CHECK-111", None)
    ticketParser.parse(github, project, repository, message) shouldNotBe Some(result)
  }
```
negative test case

File: app/module/Bootstrap.scala (hunk 2 above)
Comment (taojang) [inline app/module/Bootstrap.scala]: That was because the lines get folded in github ui :)

File: test/utility/TicketParserTest.scala (hunk 5 above)
Comment (taojang) [inline test/utility/TicketParserTest.scala]: If we would do so, then the merge commit would be invalid because by default it starts with "merge ..."

**Comment by taojang** [comment]
Code updated slightly:
* upsert problem fixed (one primary key was not marked with ```O.PrimaryKey```
* commits with parents are valid by default (merge commits)

/cc @lotharschulz

File: app/module/Production.scala [hunk 6]
```diff
@@ -9,7 +9,7 @@ import client.scm.{ GithubResolver, SCMResolver, StashResolver }
 import configuration.{ GeneralConfiguration, GeneralConfigurationImpl, OAuthConfiguration, OAuthConfigurationImpl }
 import dao.{ CommitRepository, CommitRepositoryImpl, RepoRepository, RepoRepositoryImpl }
 import play.api.Logger
-import service.{ ImportCommit, ImportCommitImpl, ImportRepositoriesImpl, ImportRepository, Search, SearchImpl }
+import service.{ ImportCommit, ImportCommitImpl, ImportRepositoriesImpl, ImportRepository, Search, SearchImpl, UpdateCommit, UpdateCommitImpl }
```
Comment (taojang) [inline app/module/Production.scala]: Codacy Issue found: [Use wildcards when selecting more than 6 elements](https://www.codacy.com/app/our1944/kontrolletti_main/file/2423172634/issues/source?bid=3159509&fileBranchId=3232854#l12)

File: app/service/UpdateCommit.scala [hunk 7]
```diff
@@ -0,0 +1,50 @@
...
+import model.Repository
+import play.api.libs.concurrent.Execution.Implicits.defaultContext
+import scala.concurrent.{ ExecutionContext, Future }
+import play.api.Logger
+
+trait UpdateCommit {
+  /**
+    * This method will re-check existing commits and apply validation
+    * It's very dangerous because it could fill up all memory.
+    * TODO: replace with stream based solution.
```
Comment (lotharschulz) [inline app/service/UpdateCommit.scala]: Is this TODO worth an issue?

**Comment by lotharschulz** [comment]
:+1:

File: app/service/UpdateCommit.scala (hunk 7 above)
Comment (taojang) [inline app/service/UpdateCommit.scala]: yes, it's definitely worth an issue.

File: app/service/ImportCommit.scala [hunk 8]
```diff
@@ -134,7 +135,7 @@ class ImportCommitImpl @Inject() (actorSystem: ActorSystem,
       commit <- commits
       result = parse(host, project, repository, commit.message) match {
         case None         => commit.copy(valid = Option(numberOfTickets(commit.tickets) > 0))
-        case Some(ticket) => commit.copy(tickets = Option(List(ticket)), valid = Option(numberOfTickets(Option(List(ticket))) > 0))
+        case Some(ticket) => commit.copy(tickets = Option(List(ticket)), valid = Option(numberOfTickets(Option(List(ticket))) > 0 || commit.parentIds.toList.nonEmpty))
```
Comment (harti2006) [inline app/service/ImportCommit.scala]: `commit.parentIds.toList.nonEmpty` shouldn't this be something like `commit.parentIds.toList.size > 1` (In case you want to mark all merge-commits as valid)? Or did I get this line wrong?

Comment (taojang) [inline app/service/ImportCommit.scala]: thx for catching this!

File: app/module/Production.scala (hunk 6 above)
Comment (taojang) [inline app/module/Production.scala]: Codacy Issue found: [Use wildcards when selecting more than 6 elements](https://www.codacy.com/app/our1944/kontrolletti_main/file/2441828546/issues/source?bid=3159509&fileBranchId=3232854#l12)

File: app/utility/GeneralHelper.scala [hunk 9]
```diff
@@ -1,12 +1,5 @@
 package utility
 
-import model.Ticket
-
 trait GeneralHelper {
```
Comment (taojang) [inline app/utility/GeneralHelper.scala]: Codacy Issue found: [Redundant braces after class definition](https://www.codacy.com/app/our1944/kontrolletti_main/file/2441828552/issues/source?bid=3159509&fileBranchId=3232854#l3)
